
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: siga
  labels:
    app: goapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapi
  template:
    metadata:
      labels:
        app: goapi
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: goapi
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
          hostPort: 443
